# Generated by Django 5.0.1 on 2024-01-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='license_plate',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='cnp',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
