# Generated by Django 5.0.1 on 2024-01-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_user_license_plate_user_address_user_cnp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='U', max_length=1),
        ),
    ]
