# Generated by Django 5.0.1 on 2024-01-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ipaddress',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
