# Generated by Django 5.0.1 on 2024-01-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_user_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='parking_slot',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
